CustomHttpClient.java

Fixes the sample client class to avoid possible NetworkOnMainThreadError exceptions

Update sample client class to fix NetworkOnMainThread exceptions

---

README.md

Small update to README so other Android devs don't run into the same problems :)

Updating README for Play Store link instructions

---

CHANGELOG.md
README.md

- Duplicate input field (Fixes Issue #201 )
- Non-Sdk Greylist warning (Fixes issue #199 )

Release v7.0.7

---

README.md

Fixes small incongruences in the public readme

Fix typos on public readme

---

CHANGELOG.md
README.md

Release v7.0.8

---

CHANGELOG.md
README.md

Release v7.0.9

---

CHANGELOG.md
README.md

Release v7.1.0

---

CHANGELOG.md
README.md

Release v7.1.1
- Custom variables not set
- Crash when parsing wrongly formatted campaign
- Custom variables now use a ConcurrentMap to prevent threading problems

Release v7.1.1

---

CHANGELOG.md
README.md

- Usabilla brand logo and redirect url with GetFeedback logo and url
- Local database to support downgrading (upon suggestion in issue #225)
- Campaigns not shown when there is a failure while parsing (Fixes issue #223)

Release v7.1.2

---

CHANGELOG.md
README.md

Release v7.2.0

---

CHANGELOG.md
README.md

- Campaign banner not shown properly in full screen apps. (Fixes issue #220)
- README to give detailed information about JAVA8 compatibility. (Fixes issue #239)

Release v7.2.1

---

CHANGELOG.md
README.md

- Image selection not working properly in ReactNative
- Optional broadcast receiver to receive user entries when a form or campaign is closed

Release v7.2.2

---

CHANGELOG.md
README.md

Release v7.6.0

---

CHANGELOG.md
README.md

Release v7.6.1

---

CHANGELOG.md
README.md

-  Accessibility issue for star rating.
- Standard event issue (app version and occurrences)
- The triggers' loading issue for the app ID which is having more that 100 campaigns

Release v7.6.4

---

CHANGELOG.md
README.md

-  Campaign reactivation enabled.

Release v7.6.5

---

CHANGELOG.md
README.md

-  Darkmode issue with custom theme

Release v7.6.6

---

CHANGELOG.md
README.md
SampleActivity.kt

- Upgrade androidMinSdkVersion to 21
- Upgrade androidTargetSdkVersion and androidCompileSdkVersion to 33
- Replace Localbroadcast manager with the sharedFlow for Kotlin and LiveData for Java 
- Increase the number of lines for questions from 3 to 5
- Remove deprecated safetynet API
- Update Google android play core API to fix duplicate classes error
- Fix the radio button issue in dark mode

Release v8.0.0

---

CHANGELOG.md
README.md
SampleActivity.kt

Release
v8.0.2 release
- Before displaying a campaign, broadcast a new event to fix the navigation buttons overlapping issue
- Updated public readme file

Release v8.0.2

---

CHANGELOG.md
README.md

Release
v8.1.0 release
- Updated public readme file
- compile and target sdk versions updated to 34
- kotlin version updated to 1.9.21
- updated AGP to 7.1.3
- Fixed high views on campaigns

Release v8.1.0

---

CHANGELOG.md
README.md
SampleActivity.kt

Release
v8.2.0 release
- Updated public readme file
- Added ```prePopulateEmailComponent```
- Fixed feedback on Android shows as 'Complete: FALSE' issue

Release v8.2.0
